Algoritmo "Ex2"
Var
n1,n2,soma,sub,multi: inteiro
divisao: real
Inicio
escreval ("Digite um número: ")
leia(n1)
escreval ("Digite outro número: ")
leia(n2)
soma<-n1+n2
multi<-n1*n2
sub<-n1-n2
divisao <-n1/n2
escreva("A soma dos números é: ")
escreval(soma)
escreva("A subtração dos números é: ")
escreval(sub)
escreva("A divisão dos números é: ")
escreval(divisao)
escreva("A multiplicação dos números é: ")
escreval(multi)
Fimalgoritmo